### ISSUE TITLE
publish on bower / npm?

### ISSUE THREAD

**Issue by MartijnR** [hareko/js-merge-xml#1]
Thanks for this library. Seems pretty useful.

Any interest in publishing this on bower and npm?

**Comment by hareko** [comment]
Thanks for your opinion.

I have not published on bower and npm before but would be interested.

**Comment by MartijnR** [comment]
Thanks for publishing! I think bower is not picking up the version somehow. Maybe the git tag isn't in the correct x.x.x format?  (bower will ignore the `"version"` property in bower.json).

Also I think including `"main": "mergexml.js"` and `"ignore" : []` in your bower.json would remove the warnings.

**Comment by hareko** [comment]
I corrected the version and bower.json but still received the warnings during the registering:

bower invalid-meta  mergexml is missing "main" entry in bower.json
bower invalid-meta  mergexml is missing "ignore" entry in bower.json

However, the info displays correctly:

C:\home\vregistry\dev\classes\mergejs>bower info mergexml
bower cached        git://github.com/hareko/js-merge-xml.git#1.1.0
bower validate      1.1.0 against git://github.com/hareko/js-merge-xml.git#*
{
  name: 'mergexml',
  homepage: 'https://github.com/hareko/js-merge-xml',
  version: '1.1.0'
}
Available versions:
  - 1.1.0

**Comment by MartijnR** [comment]
I wonder you need to commit the config.json to the repo. I always but am not sure if it's required.

**Comment by hareko** [comment]
config.json? I have package.json and bower.json

**Comment by MartijnR** [comment]
ah yes, sorry I meant bower.json. It's not in the repo.

**Comment by hareko** [comment]
I committed bower.json, unregistered/registered again and got the same warnings.
But in general, it should be ok now...

**Comment by MartijnR** [comment]
warnings are gone for me now! :+1:

**Comment by hareko** [comment]
Thanks for your time and support!
