### ISSUE TITLE
namespaced attributes are not cloned correctly

### ISSUE THREAD

**Issue by MartijnR** [hareko/js-merge-xml#10]
When setAttribute is used for namespaced attributes in conjunction with using setAttribute for declaring the namespace declaration (xmlns:...), the namespace isn't correctly set.

For example if the namespace prefix is `abc` and the namespace is `http://mynamespace.com`:

```xml
<node abc:myattr />
```

The above source can be queried like this: doc.querySelector('node').attributes[0].namespaceURI which will result in `http://mynamespace.com`.

However, when the above XML is merged into a document that doesn't contain this node or this attribute, querying the resulting document the same way as above results in `null`. The localName has changed from `myattr` to `abc:myattr`.

The solution to this bug is to use setAttributeNS to set both the attribute and the namespace declaration.

Would you be interested in a PR for this? If so, can I re-add the test framework I had added previously and that you removed?

If not interested, I'll have to publish a fork of this repo on npm. Not a problem, but I'd love to avoid this. This module is pretty popular on npm by the way! 👍

**Comment by hareko** [comment]
Thanks for pointing to this. I have worked with the php-merge-xml edition mostly.

Yes, please make the changes as you described.

**Comment by MartijnR** [comment]
My fix, seems to break IE11. Sorry about. I'll send a PR for a fixed fix.

**Comment by MartijnR** [comment]
The original bug is fixed except in Internet Explorer. For me it's fine now, but re-open if not.
