### ISSUE TITLE
Does not work in node

### ISSUE THREAD

**Issue by Arrowana** [hareko/js-merge-xml#15]
I am using nodejs v6.11.4

When I try to do anything (merging xml strings together, I get the following error:
ReferenceError: window is not defined
mergexml/mergexml.js:504:19

**Comment by hareko** [comment]
This is a browser-oriented solution using window objects DOMParser, XPathEvaluator. 

You should modify the class with the NodeJS implementations, such as xmldom, xpath.

**Comment by hareko** [comment]
Contributor is welcomed to adapt mergexml for both browser and NodeJS environments.

**Comment by dieffrei** [comment]
I needed it :(

**Comment by Sjeiti** [comment]
> This is a browser-oriented solution

You might want to state this more clearly in your readme; simply googling yields your nmp package as a top result. 
It would save a lot of people fifteen minutes of their life: installing testing, double checking, and finally finding this issue.

**Comment by hareko** [comment]
You can use MergeXML with NodeJS now - version 1.2.0 is released!

See readme about the installation and sample usage.

Your feedback is appreciated in case of any usage issues.
