### ISSUE TITLE
make commonJs, AMD module friendly?

### ISSUE THREAD

**Issue by MartijnR** [hareko/js-merge-xml#2]

**Comment by hareko** [comment]
Yes, if it improves the usability. Any recommendations?

**Comment by MartijnR** [comment]
Would be great. [Here](https://github.com/umdjs/umd) are some nice wrappers, such as this one:

```js
// if the module has no dependencies, the above pattern can be simplified to
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define([], factory);
    } else if (typeof exports === 'object') {
        // Node. Does not work with strict CommonJS, but
        // only CommonJS-like environments that support module.exports,
        // like Node.
        module.exports = factory();
    } else {
        // Browser globals (root is window)
        root.returnExports = factory();
  }
}(this, function () {

    // Just return a value to define the module export.
    // This example returns an object, but the module
    // can return a function as the exported value.
    return {};
}));
```

Let me know if you'd like a pull request. I'd be happy to do it.

**Comment by hareko** [comment]
Thanks for the wrapper. 

I modified the scripts (didn't test in AMD/CommonJS). 

How can I send you the zip?

**Comment by MartijnR** [comment]
Great!

I'd be happy to test with AMD. Easiest to just commit it to a branch, I think.

**Comment by hareko** [comment]
A new branch 'wrapped' is created.

The wrapper is added to the 'mergexml.js' and the 'example.js' is modified to recognize the wrapped class. Your checking would be great.

I have npm 2.5.1 and bower 1.3.12 available in my shell. So, I could try to publish myself in order not to spend your time (if there are no special conditions).

**Comment by MartijnR** [comment]
Thanks. I'll try to look at it today or tomorrow.

I think [this line](https://github.com/hareko/js-merge-xml/compare/wrapped#diff-d73661b25c331c84abd778ed31889540R27) could perhaps be `root.MergeXML = factory()`. That way your global variable name remains the same so you won't have to update example.js (nor your readme.md).

**Comment by hareko** [comment]
Thanks for observation - corrected.
An anonymous function could be returned on line #34 mergexml.js also.

Maybe it's better to commit to a master branch adding the change log to the readme?

**Comment by MartijnR** [comment]
:+1:  Works like a charm!

> An anonymous function could be returned on line #34 mergexml.js also.
Yes indeed. That would make a lot of sense.

I'd say it's ready to merge into master and publish on Bower (and npm). Thanks for doing this!

**Comment by hareko** [comment]
Thanks for the fixes.

Any comments regarding the publishing?
npm info mergexml
bower info mergexml

**Comment by MartijnR** [comment]
I added them to #1
