### ISSUE TITLE
capitalization

### ISSUE THREAD

**Issue by MartijnR** [hareko/js-merge-xml#3]
This is a dangerous comment, because there is no 'correct' coding style...., but I was wondering why your (non-class) functions are capitalized. I haven't seen this before.

E.g. I would normally expect `that.Init` to be `that.init` and `that.AddSource` to be `that.addSource`.

**Comment by hareko** [comment]
The function names are capitalized in order to distinguish the user functions/methods (PascalCase) from the core ones (camelCase), like AddEvent vs. addEventListener.

**Comment by MartijnR** [comment]
Ok, I see. Thanks. I think JSHint by default expects only constructors to be capitalized.
