### ISSUE TITLE
Upgrade formidable version

### ISSUE THREAD

**Issue by Alvaro948** [hareko/js-merge-xml#35]
Formidable@v1 seems to be deprecated:
- https://www.npmjs.com/package/formidable/v/1.2.1
- https://github.com/node-formidable/formidable/blob/master/VERSION_NOTES.md

**Comment by ptmkenny** [comment]
Potentially related: https://github.com/hareko/js-merge-xml/pull/24

**Comment by ptmkenny** [comment]
@hareko Thanks for fixing this quickly!  Could we please get a new release so that packages dependent on this one can point to a stable version?
