### ISSUE TITLE
variables used out of scope

### ISSUE THREAD

**Issue by MartijnR** [hareko/js-merge-xml#4]
You are often using a construct like this:
```js
if ( condition ) {
   var a = true;
}

if ( condition) {
    a = false; // here a is used out of scope.
}
```

The variable a is used out of scope in the second condition. JSHint will show you this.

but should be using:
```js
var a;
if (condition) {
   a = true
}

if ( condition ){
   a = false;
}
```

(Again, I'd be happy to send you a PR to fix the issues that JSHint finds, if you want.)

**Comment by hareko** [comment]
Thanks for pointing this out (fixed now). Your PRs are welcomed.
