### ISSUE TITLE
keep document order

### ISSUE THREAD

**Issue by MartijnR** [hareko/js-merge-xml#6]
I'm try to do this merge:

this is the data structure I want to merge into (so this is the first source I add with .AddSource())
```xml
<a>
    <r>default</r>
    <meta/>
</a>
```

this is the fragment I would like to merge into the previous data structure. It is 'incomplete' (no `<meta>`) but it contains multiple `<r>` nodes: 
```xml
<a>
   <r>override</r>
   <r/>
</a>
```

The result I'm getting is this:
```xml
<a>
    <r>override</r>
    <meta/>
    <r/>
</a>
```

The **desired** result is this:

```xml
<a>
    <r>override</r>
    <r/>
    <meta/>
</a>
```

Is there a way to get the desired result. If not, would this be a bug?

**Comment by MartijnR** [comment]
I guess both results could be valid so it's probably not a bug. I guess it would be a new feature to give precedence to sibling nodes that have the same nodeName?

**Comment by hareko** [comment]
This is not a bug - the nodes with the same path/name are replaced/added sequentially depending on the *updn* option. For your example, *new MergeXML({updn: false});* gives result:

    <a>
        <r/>
        <meta/>
    </a>

This class was created to merge the configuration files usually not having sibling nodes. The php-merge-xml is complemented with the *clone* option to use the *clone* attribute value to clone specific nodes if they already exist.

Maybe you have any ideas how to better control the sibling nodes' merging?

**Comment by hareko** [comment]
The result for your comment above is (I took the example from the emailed copy containing empty nodes only) :

    <a>
       <r>override</r>
       <meta/>
    </a>

**Comment by MartijnR** [comment]
Thanks for looking at this. I was using `updn:true` because this seemed to pick up the sibling nodes (am not sure what updn does actually).

I created this CodePen: http://codepen.io/MartijnR/pen/bdrgyy?editors=101

I don't really understand the code well enough to make a suggestion on how to give precedence to sibling nodes (with a setting) and how this would related to the updn setting. Maybe with that organize/keep-siblings-with-same-name setting, it would use insertBefore on the nextSibling of the existing node with the same name?

**Comment by hareko** [comment]
Thanks for the CodePen's creation.

I think the merging could be controlled by the following options:
- stay - the stay attribute value to deny overwriting of specific node
- clone - the clone attribute value to clone specific nodes if they already exist
- updn - traverse the nodes:
    - 0 - by overall sequence
    - 1 - by name sequence
    - 2 - by name sequence adding the nodes with the same name

The *stay* and *clone* operate node-level and *updn* operates document-level. The *stay* and *updn* (0,1) are realized already (the php version has also the *clone* option).

**Comment by MartijnR** [comment]
Maybe this belongs in a different issue, but I'd like to ask for clarification on these existing and proposed settings. I played around with it but couldn't quite figure it out. I think an example, would greatly clarify this (or tests).

I don't understand how _stay_ and _clone_ are meant to be used. Do they work on both the 1st source and 2nd source and should these attributes actually be present on nodes in the XML source(s)? 

Re. _updn_, does this relate to the first source only? Does _name sequence_ mean alphabetic nodeName sequence? I'm guessing it doesn't, but can't figure out what is the difference between overall and name sequence.

**Comment by hareko** [comment]
NB! The ArraySearch method is corrected in the mergexml.js (affects the *stay* behaviour).

The *stay* option specifies possible value(s) of the node's stay attribute ('all' by default). This is checked during the merging in 1st, 2nd,... sources and if discovered then the result node is not modified any more. That concerns the nodes of the same level, name and namespace. For example:

source1:

    <a>
        <b stay="all" opt="def">default</b>
        <c opt="def">default</c>
    </a>
source2:

    <a>
       <b opt="ovr">override</b>
       <c opt="ovr">override</c>
    </a>
result:

    <a>
       <b stay="all" opt="def">default</b>
       <c opt="ovr">override</c>
    </a>

The *clone* option/attribute should operate in the opposite direction: "don't replace but insert" if encountered.

The *updn* relates to all sources: if *true* then nodes of the same level are traversed by the nodeName (not reorderd by alphabetic sequence), else in physical sequence.  For example:

source1:

    <a>
      <c>s1</c>
      <c>s3</c>
    </a>
source2:

    <a>
      <c>s1</c>
      <b>s2</b>
      <c>s4</c>
    </a>
result (updn=true):

    <a>
      <c>s1</c>
      <c>s4</c>
      <b>s2</b>
    </a>
result (updn=false):

    <a>
      <c>s1</c>
      <c>s2</c>
      <c>s4</c>
    </a>

The *updn=2* could mean: 'clone all nodes and order by the nodeName'.

**Comment by MartijnR** [comment]
Thanks so much for explaining this. I understand it now. (The `<c>s2</c>` in the very last result should be `<b>s2</b>` I think).

For updn=2, in my example at the top, would this put the 2 `<r>` nodes ahead of the `<meta>` node?

**Comment by hareko** [comment]
The ```<c>s2</c>``` is correct, because the node values (not names) are replaced for updn=false.

It requires determination for updt=2:  to insert before or after the same node name, to skip or add identical node...

**Comment by MartijnR** [comment]
Ah I see. Wow, updn=false is an aggressive setting!

For updt=2, maybe instead of the current appending to parent it should first look for a node with the same name at the same level and insertBefore the nextSibling of that node (so after).

**Comment by hareko** [comment]
Yes, the nodes are compared on the same level. I'd also add after the existing node.

Is there any particular need for this option?

**Comment by MartijnR** [comment]
I have this need, to deal with the `<repeat>` feature in XForms. I am using your library to merge a record into a default model. The record may contain more repeat instances than the default model. Although your library currently merges all the nodes and values, it changes the data structure (the order) of the model. This would break form logic that uses more complex XPath axes, such as preceding-sibling:: where the document order is important.

I am not sure if there is a more general need... But I guess when sibling nodes with the same name are used in any XML Document, they would be expected to be grouped together. Maybe not always, but more often than not?

**Comment by hareko** [comment]
MergeXML should be improved with the option updn=2 grouping together the nodes with the same name on the same level in the alphabetic order. I can't say at the moment when I have the time to delve into this.

For more sophisticated structures there is a question about the balance between universality and complexity. Either to add functionality to existing class or  create a new one. That requires some time and investigation. Maybe you'd like to outsource the merge part of your project?

**Comment by MartijnR** [comment]
> in the alphabetic order
Why in alphabetic order? I don't think there is ever any reason to order nodes alphabetically. That's definitely not what I'm after.

I am wondering if instead creating a new updn mode, you could add this as the behaviour in updn = true. It seems it would be more valid.

Regarding outsourcing, yes that's a totally valid point. My only concern is the admin overhead. Would you like to send me a quote by email (when our requirements are clear) and I can see whether it would make sense to me?

**Comment by hareko** [comment]
Ok, it should be ordered as **desired** result in your 1st comment. 

The class has functionality that I needed in my applications. Your comments help to make it more widely applicable. 

Yes, we can talk about the quotes when the requirements are clear. Would you email the specification to assess the amount of work?

**Comment by MartijnR** [comment]
I was thinking to add a test framework with a few tests of the current functionality. Would you like such a PR (using karma)?

If so, I could subsequently add some specs that test for the functionality I propose in this thread, which would then describe the requirements. How does that sound?

I may also try to give it a quick shot to implement it, but we'll see.

**Comment by hareko** [comment]
I have not  practiced TDD particularly but have node.js and Karma installed in my dev PC. 

If the test framework helps in specifying requirements and development then of course, it makes sense.

**Comment by hareko** [comment]
If the requirements are not very complicated then the class could be extended without special tests.
How do you think?

**Comment by MartijnR** [comment]
Right, they're not very complicated. Would be good anyway to have tests
though, maybe? It won't take long to do. I'm hoping to do it this week or
next week. I like karma (with grunt) as you can test 4 different browsers
just with one command.

On Wed, Jul 1, 2015 at 1:09 PM, Vallo Reima <notifications@github.com>
wrote:

> If the requirements are not very complicated then the class could be
> extended without special tests.
> How do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hareko/js-merge-xml/issues/6#issuecomment-117797754>.
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by hareko** [comment]
Thanks for the tests. I merged with the master.

**Comment by MartijnR** [comment]
I recently realized there is a more serious issue related to repeats in XForms. The solution to both issues seemed better dealt with outside of this library (a kind of pre-processing before merging).

So all is good! 

Thanks again for the great tool you built!
