### ISSUE TITLE
"main" in package.json incorrect

### ISSUE THREAD

**Issue by MartijnR** [hareko/js-merge-xml#9]
It should be "main": "mergexml.js".

https://docs.npmjs.com/files/package.json#main

**Comment by hareko** [comment]
I see the current package.json contains "main": "mergexml.js"

I haven't looked yet your tests more detailed (dealing with other project). But if you are interested in outsourcing your XForms solution, let me know

**Comment by MartijnR** [comment]
Oops sorry. It seems this issue is cause by #8 (just need to publish latest version).

The current version on npm has: `"main": "example.html".

No need for any more customizations. Dealing with `repeats` in XForms is so weird that it didn't make sense to add it to your library. Instead I'm doing some preprocessing before using your library. Works marvelously!
